"""baseline schema

Revision ID: aec45213e565
Revises: 
Create Date: 2026-04-20 16:04:14.992396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec45213e565'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(), nullable=False),
    sa.Column('batch_name', sa.String(), nullable=True),
    sa.Column('batch_type', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.Date(), nullable=True),
    sa.Column('warn_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_code')
    )
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('scheduler_run_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('current_package_name', sa.String(), nullable=True),
    sa.Column('current_fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_expire_at', sa.Date(), nullable=True),
    sa.Column('source_expire_at', sa.Date(), nullable=True),
    sa.Column('last_charge_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_no')
    )
    op.create_table('system_config',
    sa.Column('config_key', sa.String(), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('config_key')
    )
    op.create_table('alert_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('related_batch_id', sa.Integer(), nullable=True),
    sa.Column('related_student_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_batch_id'], ['account_batch.id'], ),
    sa.ForeignKeyConstraint(['related_student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('file_checksum', sa.String(), nullable=True),
    sa.Column('sheet_name', sa.String(), nullable=True),
    sa.Column('mapping_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.String(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mobile_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('disabled_reason', sa.String(), nullable=True),
    sa.Column('last_assigned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['account_batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account')
    )
    op.create_table('binding_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('old_mobile_account_id', sa.Integer(), nullable=True),
    sa.Column('new_mobile_account_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('old_expire_at', sa.Date(), nullable=True),
    sa.Column('new_expire_at', sa.Date(), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['new_mobile_account_id'], ['mobile_account.id'], ),
    sa.ForeignKeyConstraint(['old_mobile_account_id'], ['mobile_account.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_binding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('mobile_account_id', sa.Integer(), nullable=False),
    sa.Column('bind_source', sa.String(), nullable=False),
    sa.Column('bind_type', sa.String(), nullable=False),
    sa.Column('bind_at', sa.DateTime(), nullable=False),
    sa.Column('expire_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mobile_account_id'], ['mobile_account.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile_account_id', name='uq_current_binding_mobile_account'),
    sa.UniqueConstraint('student_id', name='uq_current_binding_student')
    )
    op.create_table('import_job_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_import_job_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('last_processed_charge_time_before', sa.DateTime(), nullable=True),
    sa.Column('last_processed_charge_time_after', sa.DateTime(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['admin_user.id'], ),
    sa.ForeignKeyConstraint(['source_import_job_id'], ['import_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('export_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_batch_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_user.id'], ),
    sa.ForeignKeyConstraint(['operation_batch_id'], ['operation_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_batch_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_batch_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_no', sa.String(), nullable=True),
    sa.Column('student_name', sa.String(), nullable=True),
    sa.Column('action_plan', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('old_mobile_account_id', sa.Integer(), nullable=True),
    sa.Column('new_mobile_account_id', sa.Integer(), nullable=True),
    sa.Column('old_expire_at', sa.Date(), nullable=True),
    sa.Column('new_expire_at', sa.Date(), nullable=True),
    sa.Column('charge_time', sa.DateTime(), nullable=True),
    sa.Column('package_name', sa.String(), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('export_included', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['new_mobile_account_id'], ['mobile_account.id'], ),
    sa.ForeignKeyConstraint(['old_mobile_account_id'], ['mobile_account.id'], ),
    sa.ForeignKeyConstraint(['operation_batch_id'], ['operation_batch.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_batch_detail')
    op.drop_table('export_job')
    op.drop_table('operation_batch')
    op.drop_table('import_job_error')
    op.drop_table('current_binding')
    op.drop_table('binding_history')
    op.drop_table('mobile_account')
    op.drop_table('import_job')
    op.drop_table('audit_log')
    op.drop_table('alert_record')
    op.drop_table('system_config')
    op.drop_table('student')
    op.drop_table('scheduler_run_log')
    op.drop_table('admin_user')
    op.drop_table('account_batch')
    # ### end Alembic commands ###
